# Reference: https://github.com/i3/i3/blob/next/etc/config

config-version = 2

# In i3, all workspaces are phantom
persistent-workspaces = []

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

[mode.main.binding]
    alt-backtick = 'mode oneshot'
    cmd-shift-m  = 'fullscreen'
    alt-shift-backtick = 'mode modal'


[mode.oneshot.binding]
    h            = ['focus --boundaries-action wrap-around-the-workspace left', 'mode main']
    j            = ['focus --boundaries-action wrap-around-the-workspace down', 'mode main']
    k            = ['focus --boundaries-action wrap-around-the-workspace up', 'mode main']
    l            = ['focus --boundaries-action wrap-around-the-workspace right', 'mode main']

    shift-h      = ['move left', 'mode main']
    shift-j      = ['move down', 'mode main']
    shift-k      = ['move up', 'mode main']
    shift-l      = ['move right', 'mode main']


    f            = ['fullscreen', 'mode main']
    b            = ['balance-sizes', 'mode main']

    slash        = ['layout tiles horizontal vertical',  'mode main']

    space        = ['layout floating tiling', 'mode main']

    1            = ['workspace 1', 'mode main']
    2            = ['workspace 2', 'mode main']
    3            = ['workspace 3', 'mode main']
    4            = ['workspace 4', 'mode main']
    5            = ['workspace 5', 'mode main']
    6            = ['workspace 6', 'mode main']
    7            = ['workspace 7', 'mode main']
    8            = ['workspace 8', 'mode main']
    9            = ['workspace 9', 'mode main']
    0            = ['workspace 10', 'mode main']

    shift-1      = ['move-node-to-workspace 1', 'mode main']
    shift-2      = ['move-node-to-workspace 2', 'mode main']
    shift-3      = ['move-node-to-workspace 3', 'mode main']
    shift-4      = ['move-node-to-workspace 4', 'mode main']
    shift-5      = ['move-node-to-workspace 5', 'mode main']
    shift-6      = ['move-node-to-workspace 6', 'mode main']
    shift-7      = ['move-node-to-workspace 7', 'mode main']
    shift-8      = ['move-node-to-workspace 8', 'mode main']
    shift-9      = ['move-node-to-workspace 9', 'mode main']
    shift-0      = ['move-node-to-workspace 10', 'mode main']

    alt-1 = ['move-node-to-workspace 1', 'workspace 1', 'mode main']
    alt-2 = ['move-node-to-workspace 2', 'workspace 2', 'mode main']
    alt-3 = ['move-node-to-workspace 3', 'workspace 3', 'mode main']
    alt-4 = ['move-node-to-workspace 4', 'workspace 4', 'mode main']
    alt-5 = ['move-node-to-workspace 5', 'workspace 5', 'mode main']
    alt-6 = ['move-node-to-workspace 6', 'workspace 6', 'mode main']
    alt-7 = ['move-node-to-workspace 7', 'workspace 7', 'mode main']
    alt-8 = ['move-node-to-workspace 8', 'workspace 8', 'mode main']
    alt-9 = ['move-node-to-workspace 9', 'workspace 9', 'mode main']
    alt-0 = ['move-node-to-workspace 10', 'workspace 10', 'mode main']

    alt-shift-h  = ['join-with left', 'mode main']
    alt-shift-j  = ['join-with down', 'mode main']
    alt-shift-k  = ['join-with up', 'mode main']
    alt-shift-l  = ['join-with right', 'mode main']

    r            = ['reload-config', 'mode main']
    alt-r        = ['mode resize', 'mode main']

    enter        = ['mode main', 'mode main']
    esc          = ['mode main', 'mode main']
    alt-backtick = ['mode main', 'mode main']
    backtick     = ['workspace-back-and-forth', 'mode main']

    e            = ['workspace e', 'mode main']
    t            = ['workspace t', 'mode main']
    z            = ['workspace z', 'mode main']
    s            = ['workspace s', 'mode main']
    shift-e      = ['move-node-to-workspace e', 'mode main']
    shift-t      = ['move-node-to-workspace t', 'mode main']
    shift-z      = ['move-node-to-workspace z', 'mode main']
    shift-s      = ['move-node-to-workspace s', 'mode main']
    alt-e        = ['move-node-to-workspace e', 'workspace e', 'mode main']
    alt-t        = ['move-node-to-workspace t', 'workspace t', 'mode main']
    alt-z        = ['move-node-to-workspace z', 'workspace z', 'mode main']
    alt-s        = ['move-node-to-workspace s', 'workspace s', 'mode main']

[mode.modal.binding]
    # i3 wraps focus by default
    h =         'focus --boundaries-action wrap-around-the-workspace left'
    j =         'focus --boundaries-action wrap-around-the-workspace down'
    k =         'focus --boundaries-action wrap-around-the-workspace up'
    l = 'focus --boundaries-action wrap-around-the-workspace right'

    shift-h = 'move left'
    shift-j = 'move down'
    shift-k = 'move up'
    shift-l = 'move right'

    # Consider using 'join-with' command as a 'split' replacement if you want to enable
    # normalizations
    # alt-h = 'split horizontal'
    # alt-v = 'split vertical'

    f = 'fullscreen'
    b = 'balance-sizes'

    slash = 'layout tiles horizontal vertical' # 'layout toggle split' in i3
    space = 'layout floating tiling' # 'floating toggle' in i3

    # Not supported, because this command is redundant in AeroSpace mental model.
    # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
    #alt-space = 'focus toggle_tiling_floating'

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # alt-a = 'focus parent'

    1 = 'workspace 1'
    2 = 'workspace 2'
    3 = 'workspace 3'
    4 = 'workspace 4'
    5 = 'workspace 5'
    6 = 'workspace 6'
    7 = 'workspace 7'
    8 = 'workspace 8'
    9 = 'workspace 9'
    0 = 'workspace 10'


    shift-1 = 'move-node-to-workspace 1'
    shift-2 = 'move-node-to-workspace 2'
    shift-3 = 'move-node-to-workspace 3'
    shift-4 = 'move-node-to-workspace 4'
    shift-5 = 'move-node-to-workspace 5'
    shift-6 = 'move-node-to-workspace 6'
    shift-7 = 'move-node-to-workspace 7'
    shift-8 = 'move-node-to-workspace 8'
    shift-9 = 'move-node-to-workspace 9'
    shift-0 = 'move-node-to-workspace 10'


    alt-1 = ['move-node-to-workspace 1', 'workspace 1']
    alt-2 = ['move-node-to-workspace 2', 'workspace 2']
    alt-3 = ['move-node-to-workspace 3', 'workspace 3']
    alt-4 = ['move-node-to-workspace 4', 'workspace 4']
    alt-5 = ['move-node-to-workspace 5', 'workspace 5']
    alt-6 = ['move-node-to-workspace 6', 'workspace 6']
    alt-7 = ['move-node-to-workspace 7', 'workspace 7']
    alt-8 = ['move-node-to-workspace 8', 'workspace 8']
    alt-9 = ['move-node-to-workspace 9', 'workspace 9']
    alt-0 = ['move-node-to-workspace 10', 'workspace 10']

    alt-shift-h = 'join-with left'
    alt-shift-j = 'join-with down'
    alt-shift-k = 'join-with up'
    alt-shift-l = 'join-with right'

    alt-shift-c = 'reload-config'
    alt-r = 'mode resize'

    enter = 'mode main'
    esc = 'mode main'
    alt-backtick = 'mode main'
    backtick = 'workspace-back-and-forth'


    e = 'workspace e'
    t = 'workspace t'
    z = 'workspace z'
    s = 'workspace s'
    shift-e = 'move-node-to-workspace e'
    shift-t = 'move-node-to-workspace t'
    shift-z = 'move-node-to-workspace z'
    shift-s = 'move-node-to-workspace s'
    alt-e = ['move-node-to-workspace e', 'workspace e']
    alt-t =  ['move-node-to-workspace t', 'workspace t']
    alt-z = ['move-node-to-workspace z', 'workspace z']
    alt-s =  ['move-node-to-workspace s', 'workspace s']


[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

[[on-window-detected]]
    if.app-id = 'org.gnu.Emacs'
    check-further-callbacks = true
    run = ['move-node-to-workspace e']

[[on-window-detected]]
    if.app-id = 'net.kovidgoyal.kitty'
    check-further-callbacks = true
    run = ['move-node-to-workspace t']

[[on-window-detected]]
    if.app-id = 'app.zen-browser.zen'
    check-further-callbacks = true
    run = ['move-node-to-workspace z']

[[on-window-detected]]
    if.app-id = 'com.tinyspeck.slackmacgap'
    check-further-callbacks = true
    run = ['move-node-to-workspace s']
