(add-to-list 'load-path "~/.emacs.d/custom")
(require 'dependencies-setup)
(require 'evil-tweaks)
(require 'modeline-tweaks)
(require 'linum-relativenumber)
(require 'ac-tweaks)
(require 'misc-tweaks)
