(add-to-list 'load-path "~/.emacs.d/custom")
(require 'dependencies-setup)
(require 'evil-tweaks)
(require 'modeline-tweaks)
(require 'ac-tweaks)
(require 'smartparens-tweaks)
(require 'dictem-setup)
(require 'mpris-defuns)
(require 'misc-tweaks)
(require 'linum-relativenumber)
