# Begin file
## zprof for profiling
# zmodload zsh/zprof


# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


#custom key bindings
# VI MODE KEYBINDINGS (ins mode)
bindkey -M viins '^a'    beginning-of-line
bindkey -M viins '^e'    end-of-line
bindkey -M viins '^b'    backward-char
bindkey -M viins '^f'    forward-char
bindkey -M viins '^k'    kill-line
bindkey -M viins '^r'    history-incremental-pattern-search-backward
bindkey -M viins '^s'    history-incremental-pattern-search-forward
bindkey -M viins '^p'    history-substring-search-up
bindkey -M viins '^n'    history-substring-search-down
bindkey -M viins '^y'    yank
bindkey -M viins '^w'    backward-kill-word
bindkey -M viins '^u'    backward-kill-line
bindkey -M viins '^h'    backward-delete-char
bindkey -M viins '^?'    backward-delete-char
bindkey -M viins '^_'    undo
bindkey -M viins '^x^r'  redisplay
bindkey -M viins '\eOH'  beginning-of-line                 # Home
bindkey -M viins '\eOF'  end-of-line                       # End
bindkey -M viins '\e[2~' overwrite-mode                    # Insert
bindkey -M viins '\ef'   forward-word                      # Alt-f
bindkey -M viins '\eb'   backward-word                     # Alt-b
bindkey -M viins '\ed'   kill-word                         # Alt-d
bindkey -M viins '\e^h'  backward-kill-word                # Alt-backspace
bindkey -M viins '\e^?'  backward-kill-word                # Alt-backspace
bindkey -M viins 'jk'    vi-cmd-mode
bindkey -M viins '\e.'   insert-last-word

# VI MODE KEYBINDINGS (cmd mode)
bindkey -M vicmd '^a'    beginning-of-line
bindkey -M vicmd '^e'    end-of-line
bindkey -M vicmd '^k'    kill-line
bindkey -M vicmd '^r'    history-incremental-pattern-search-backward
bindkey -M vicmd '^s'    history-incremental-pattern-search-forward
bindkey -M vicmd '^p'    up-line-or-history
bindkey -M vicmd '^n'    down-line-or-history
bindkey -M vicmd '^y'    yank
bindkey -M vicmd '^w'    backward-kill-word
bindkey -M vicmd '^u'    backward-kill-line
bindkey -M vicmd '/'     vi-history-search-forward
bindkey -M vicmd '?'     vi-history-search-backward
bindkey -M vicmd '^_'    undo
bindkey -M vicmd '\ef'   forward-word                      # Alt-f
bindkey -M vicmd '\eb'   backward-word                     # Alt-b
bindkey -M vicmd '\ed'   kill-word                         # Alt-d
bindkey -M vicmd '\e[5~' history-beginning-search-backward # PageUp
bindkey -M vicmd '\e[6~' history-beginning-search-forward  # PageDown
bindkey -M vicmd '\e^h'  backward-kill-word                # Alt-backspace
bindkey -M vicmd '\e^?'  backward-kill-word                # Alt-backspace
bindkey -M vicmd '\e.'   insert-last-word

#aliases
alias .='cd ../'
alias ..='cd ../../'
alias ...='cd ../../../'
alias ....='cd ../../../../'

alias fget='aria2c -c --max-connection-per-server=8 --min-split-size=1M'
alias en='emacsclient -t -a vim'
alias e='emacsclient -n -a vim'
alias v='vim'
alias ssa='ssh'
alias dsdb='udisksctl unmount --block-device /dev/sdb1;udisksctl unmount --block-device /dev/sdb2;udisks --detach /dev/sdb;'
alias cnet='ping 8.8.8.8'
alias zshconfig='emacsclient -t -a 'vim' ~/.zshrc'
alias wn='dict -d wn'
alias ff='fd'
alias imdb='/usr/bin/lm'
alias cmyip="curl ifconfig.me"

#systemd alias
alias restart='sudo systemctl restart'
alias status='sudo systemctl status'
alias start='sudo systemctl start'
alias stop='sudo systemctl stop'
alias flix='flix -port 6060 -player mpv'

#custom functions
sortdiff() {
  bash -c "diff <(sort $1) <(sort $2)"
}

sortmeld() {
  bash -c "meld <(sort $1) <(sort $2)"
}

function ediff() {
	if [ "X${2}" = "X" ]; then
		echo "USAGE: ediff <FILE 1> <FILE 2>"
	else
		# The --eval flag takes lisp code and evaluates it with EMACS
		emacsclient -n --eval "(progn (ediff-files \"$1\" \"$2\") )" > /dev/null 2>&1
    hs -c 'hs.application.get("Emacs"):activate();' > /dev/null 2>&1
	fi
}

#ENVIRONMENT VARS
export TERM=screen-256color
export LANG="en_US.UTF-8"
export EDITOR="/usr/local/bin/emacsclient -c -a vim"
export VISUAL="emacsclient -c -a vim"
export GREP_COLOR='1;34'
export SHELL="/bin/zsh"
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND=(fg=blue)
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND=(fg=red)


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


source /usr/local/share/gem_home/gem_home.sh

# Update homebrew only once a day, not every 60 secs(default)
export HOMEBREW_AUTO_UPDATE_SECS=86400

if [[ -z $TMUX ]]; then
  path=(
    # Personal
    "$HOME/.local/bin"
    # existing path
    $path
    # Android
    # /opt/android-sdk/tools
    # Rust
    "$HOME/.cargo/bin"
    "/Users/ayush/Work/Repos/poneglyph/bin"
  )


  # jenv
  _evalcache jenv init - zsh

  # pyenv. (NOT using zprezto python module as it is very slow)

  # Gem Home env can be loaded just once
 # gem_home ~/.gem/global; pushd ~
 # chruby system

fi

#custom fasd settings. prezto settings primitive
_evalcache zoxide init zsh
_evalcache atuin init zsh
#_evalcache pyenv init -
#_evalcache pyenv virtualenv-init -

## Finish zprof, by printing
# zprof

alias urldecode='python3 -c "import sys, urllib.parse as ul; print(ul.unquote_plus(sys.argv[1]))"'
alias urlencode='python3 -c "import sys, urllib.parse as ul; print(ul.quote_plus(sys.argv[1]))"'

export VISUAL=vim
autoload edit-command-line; zle -N edit-command-line
bindkey -M vicmd v edit-command-line
export EMACS_SOCKET_NAME=~/.emacs.d/server/server

