#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#custom key bindings
bindkey -M viins 'jk' vi-cmd-mode
bindkey -M viins '\e.' insert-last-word

#aliases
alias .='cd ../'
alias ..='cd ../../'
alias ...='cd ../../../'
alias ....='cd ../../../../'

alias fget='aria2c -c --max-connection-per-server=8 --min-split-size=1M'
alias e='emacsclient -t'
alias en='emacs -nw'
alias v='vim'
alias ssa='ssh -l ayush.go'
alias dsdb='udisksctl unmount --block-device /dev/sdb1;udisksctl unmount --block-device /dev/sdb2;udisks --detach /dev/sdb;'
alias cnet='ping 8.8.8.8'
alias zshconfig='emacsclient -t -a 'nano' ~/.zshrc'
alias wn='dict -d wn'

#ENVIRONMENT VARS
export TERM=xterm-256color
export EDITOR=vim
export VISUAL=vim
export GREP_COLOR='1;34'
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND=(fg=blue)
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND=(fg=red)

#custom fasd settings. prezto settings primitive
eval "$(fasd --init auto)"

alsi -a -u
